-- =====================================================================
-- Dubai Real Estate Data Warehouse : star schema DDL
-- Portable ANSI-style SQL (tested on SQLite; runs on PostgreSQL / MySQL /
-- SQL Server with minor type tweaks, e.g. DATE, VARCHAR, DECIMAL).
-- Surrogate keys are generated by the ETL layer, not by the database,
-- so there are no AUTOINCREMENT / IDENTITY dialect differences.
-- =====================================================================

-- ---------- STAGING (raw, as received) ------------------------------
CREATE TABLE IF NOT EXISTS stg_transactions (
    transaction_id    VARCHAR(20),
    instance_date     VARCHAR(20),
    area_id           INTEGER,
    area_name_en      VARCHAR(100),
    prop_type_en      VARCHAR(30),
    rooms_en          VARCHAR(20),
    offplan           VARCHAR(20),
    trans_group_en    VARCHAR(30),
    buyer_type        VARCHAR(30),
    procedure_area    DECIMAL(12,2),
    actual_worth      DECIMAL(16,2),
    _batch_id         VARCHAR(40),
    _loaded_at        VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS stg_area_master (
    area_id        INTEGER,
    area_name_en   VARCHAR(100),
    community      VARCHAR(100),
    zone           VARCHAR(50),
    effective_date VARCHAR(20),
    _batch_id      VARCHAR(40)
);

-- ---------- DIMENSIONS ----------------------------------------------
CREATE TABLE IF NOT EXISTS dim_date (
    date_key        INTEGER PRIMARY KEY,        -- yyyymmdd
    full_date       DATE        NOT NULL,
    day_of_month    INTEGER     NOT NULL,
    day_name        VARCHAR(10) NOT NULL,
    day_of_week     INTEGER     NOT NULL,       -- 1=Mon .. 7=Sun (sort key for day_name)
    is_weekend      INTEGER     NOT NULL,       -- UAE weekend = Sat/Sun
    week_of_year    INTEGER     NOT NULL,
    month_num       INTEGER     NOT NULL,
    month_name      VARCHAR(10) NOT NULL,
    year_month      VARCHAR(7)  NOT NULL,       -- 2026-03
    quarter_num     INTEGER     NOT NULL,
    quarter_label   VARCHAR(7)  NOT NULL,       -- 2026-Q1
    year_num        INTEGER     NOT NULL
);

-- SCD Type 2: one row per (area, version of its attributes)
CREATE TABLE IF NOT EXISTS dim_area (
    area_key      INTEGER PRIMARY KEY,          -- surrogate key
    area_id       INTEGER      NOT NULL,        -- natural / business key
    area_name     VARCHAR(100) NOT NULL,
    community     VARCHAR(100),
    zone          VARCHAR(50),
    valid_from    DATE         NOT NULL,
    valid_to      DATE         NOT NULL,        -- 9999-12-31 while current
    is_current    INTEGER      NOT NULL,
    row_hash      VARCHAR(32)  NOT NULL         -- change detection
);

CREATE TABLE IF NOT EXISTS dim_property (
    property_key   INTEGER PRIMARY KEY,
    property_type  VARCHAR(30) NOT NULL,
    rooms          VARCHAR(20) NOT NULL,
    sale_stage     VARCHAR(20) NOT NULL         -- Off-Plan / Ready
);

CREATE TABLE IF NOT EXISTS dim_buyer_type (
    buyer_type_key INTEGER PRIMARY KEY,
    buyer_type     VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_transaction_type (
    txn_type_key   INTEGER PRIMARY KEY,
    txn_type       VARCHAR(30) NOT NULL
);

-- ---------- FACT ----------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_transactions (
    transaction_key      INTEGER PRIMARY KEY,
    transaction_id       VARCHAR(20)  NOT NULL UNIQUE,  -- degenerate dimension
    date_key             INTEGER      NOT NULL REFERENCES dim_date(date_key),
    area_key             INTEGER      NOT NULL REFERENCES dim_area(area_key),
    property_key         INTEGER      NOT NULL REFERENCES dim_property(property_key),
    buyer_type_key       INTEGER      NOT NULL REFERENCES dim_buyer_type(buyer_type_key),
    txn_type_key         INTEGER      NOT NULL REFERENCES dim_transaction_type(txn_type_key),
    transaction_value    DECIMAL(16,2) NOT NULL,        -- AED
    area_sqm             DECIMAL(12,2) NOT NULL,
    price_per_sqm        DECIMAL(14,2) NOT NULL,        -- derived at load time
    _batch_id            VARCHAR(40)  NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fact_date     ON fact_transactions(date_key);
CREATE INDEX IF NOT EXISTS ix_fact_area     ON fact_transactions(area_key);
CREATE INDEX IF NOT EXISTS ix_fact_property ON fact_transactions(property_key);
CREATE INDEX IF NOT EXISTS ix_fact_buyer    ON fact_transactions(buyer_type_key);
CREATE INDEX IF NOT EXISTS ix_fact_txntype  ON fact_transactions(txn_type_key);
CREATE INDEX IF NOT EXISTS ix_area_bk       ON dim_area(area_id, valid_from);

-- ---------- OPERATIONAL / AUDIT -------------------------------------
CREATE TABLE IF NOT EXISTS reject_transactions (
    transaction_id VARCHAR(20),
    reject_reason  VARCHAR(100),
    _batch_id      VARCHAR(40),
    _rejected_at   VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS dq_log (
    run_id      VARCHAR(40),
    check_name  VARCHAR(100),
    status      VARCHAR(10),        -- PASS / FAIL / WARN
    detail      VARCHAR(300),
    checked_at  VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS etl_run_log (
    run_id          VARCHAR(40),
    started_at      VARCHAR(30),
    finished_at     VARCHAR(30),
    rows_extracted  INTEGER,
    rows_rejected   INTEGER,
    rows_duplicate  INTEGER,
    rows_loaded     INTEGER,
    status          VARCHAR(10),
    duration_sec    DECIMAL(10,2)
);

-- High-water mark for incremental loads
CREATE TABLE IF NOT EXISTS etl_state (
    pipeline        VARCHAR(40) PRIMARY KEY,
    last_loaded_date DATE
);
